version: "2.1"
services:
  pwndrop:
    image: lscr.io/linuxserver/pwndrop
    container_name: pwndrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SECRET_PATH=/pwndrop #optional
    volumes:
      - pwndrop_config:/config
    ports:
      - 8080:8080
    restart: unless-stopped